basePath: /
host: localhost:8080
info:
  contact:
    email: support@example.com
    name: API Support
    url: https://github.com/mohamedfawas/api-gateway-qubool-kallyaanam
  description: A microservice gateway for the Qubool Kallyaanam application
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Qubool Kallyaanam API Gateway
  version: "1.0"
paths: {}
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and the JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
